version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  disable:
    - errcheck        # Too noisy for this codebase
  enable:
    # Additional linters (default linters are enabled automatically)
    - misspell        # Spell checking
    - nilerr          # nil error checks

formatters:
  enable:
    - goimports

settings:
  goimports:
    local-prefixes:
      - github.com/d2verb/alpaca

  govet:
    enable-all: true

  misspell:
    locale: US

issues:
  exclude-rules:
    # Ignore test files for some linters
    - path: _test\.go
      linters:
        - errcheck
        - govet

  max-issues-per-linter: 0
  max-same-issues: 0
