version: "2"

run:
  timeout: 5m

linters:
  disable:
    - errcheck # Too noisy for this codebase
  enable:
    - misspell # Spell checking
    - nilerr # nil error checks

formatters:
  enable:
    - goimports
