version: 2

project_name: alpaca

before:
  hooks:
    - go mod tidy

builds:
  - id: alpaca
    main: ./cmd/alpaca
    binary: alpaca
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}

archives:
  - id: alpaca
    ids:
      - alpaca
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'

changelog:
  use: github-native

homebrew_casks:
  - name: alpaca
    directory: Casks
    repository:
      owner: d2verb
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    homepage: https://github.com/d2verb/alpaca
    description: Lightweight llama-server wrapper for macOS
    license: MIT
