version: 2

project_name: alpaca

before:
  hooks:
    - go mod tidy

builds:
  - id: alpaca
    main: ./cmd/alpaca
    binary: alpaca
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}

archives:
  - id: alpaca
    ids:
      - alpaca
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'

changelog:
  use: github-native

brews:
  - name: alpaca
    directory: Formula
    repository:
      owner: d2verb
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    homepage: https://github.com/d2verb/alpaca
    description: Lightweight llama-server wrapper for macOS
    license: MIT
    install: |
      bin.install "alpaca"
    post_install: |
      require "digest"
      require "json"
      require "fileutils"

      receipt_dir = "#{ENV["HOME"]}/.alpaca"
      FileUtils.mkdir_p(receipt_dir)

      binary_path = "#{bin}/alpaca"
      fingerprint = Digest::SHA256.file(binary_path).hexdigest
      timestamp = Time.now.utc.iso8601

      receipt = {
        schema_version: 1,
        install_source: "brew",
        installed_at: timestamp,
        binary_path: binary_path,
        binary_fingerprint: "sha256:#{fingerprint}"
      }

      File.write("#{receipt_dir}/install.json", JSON.pretty_generate(receipt))
